name: Cypress Regression Tests Backend

on: [push]

jobs:

  Testes_Backend:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Subindo Ambiente'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          config-file: cypress.config.js
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          record: true
          group: 'Backend Tests'
          spec: cypress/e2e/*
          
      - name: 'Rodando Testes'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn test
          config-file: cypress.config.js
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          record: true
          group: 'Backend Tests'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
